# -*- coding: utf-8 -*-
"""Ejercicios en clase sesion 03/09/2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSuiIjqlMby1HEzMNldZPSvhbXXxUu_N

A. De la lógica a la decisión
Condiciones simples y estructuras if / else
"""

#Completa una decisión simple
#Completa la condición para mostrar “Mayor de edad” cuando la variable edad sea mayor o
#igual a 18
Edad = 20
if Edad >= 18:
    print("Mayor de edad")

#Agrega la ruta alternativa
#Completa la estructura para clasificar una temperatura como “Alta” si supera 30 grados y
#“Normal” en caso contrario
Temperatura =32
if Temperatura > 30:
  print("Alta")
else:
  print("Normal")

#Predice la salida
#Sin ejecutar, escribe exactamente qué imprimirá el programa.
Numero = 7
if Numero % 2 == 0:
  print("Par")
else:
  print("Impar")
# print Impar

"""B. Múltiples condiciones
if / elif / else y orden de evaluación
"""

#Completa la clasificación
#Agrega las dos expresiones faltantes para clasificar la nota
Nota = 4.2
if Nota >= 4.5:
  print ("Excelente")
elif Nota >=4.0:
  print ("Muy buen desempeño")
elif Nota >=3.0:
  print ("Aprobado")
else:
  print ("No Aprobado")

#Corrige el orden
#El programa pretende mostrar “Excelente” para notas de 4.5 o más. Reescribe únicamente el
#bloque condicional en el orden correcto
#Pista: Python evalúa de arriba hacia abajo y ejecuta la primera condición verdadera.

Nota =4.8
if Nota >=4.5:
  print ("Excelente")
elif Nota >=3.0:
  print ("Aprobado")
else:
  print ("No Aprobado")

#Traza la ejecución
#Escribe la salida para valor = 12. Después indica cuál condición fue la primera verdadera
# Respuesta: Salida "C" elif valor < 15:
valor = 12
if valor < 5:
 print("A")
elif valor < 10:
 print("B")
elif valor < 15:
 print("C")
else:
 print("D")

"""C. Operadores lógicos
Construye condiciones con and, or y not

"""

#Acceso con dos requisitos
#Completa el operador lógico para permitir acceso solo cuando ambas variables sean
#verdaderas.
Usuario_activo = True
Tiene_permiso = True
if Usuario_activo and Tiene_permiso:
  print("Acceso Permitido")
else:
  print("Acceso Denegado")

#Dos rutas válidas
#Completa la condición: se permite continuar si existe correo válido o teléfono válido.

Correo_valido = True
Telefono_valido = False
if Correo_valido or Telefono_valido:
  print("Continuar Registro")
else:
  print("Faltan Datos de Contacto")

#Usa negación
#Completa la condición usando not para mostrar el mensaje solo si la cuenta NO está
#bloqueada.
Cuenta_bloqueada = False
if not Cuenta_bloqueada:
  print("Puede Operar")

"""D. Estructura repetitiva for
Recorrer rangos y controlar iteraciones
"""

#Recorre del 1 al 5
#Completa range() para imprimir los valores 1, 2, 3, 4 y 5.

for numero in range (1,6):
  print(numero)

#Recorre con paso
#Completa range() para imprimir 2, 4, 6, 8 y 10.

for numero in range (2,11,2):
  print(numero)

#Predice el acumulado
#Sin ejecutar, determina el valor final de suma.
#

suma = 0
for i in range(1, 4):
 suma = suma + i
print(suma)

"""E. Estructura repetitiva while
Repetir mientras una condición permanezca verdadera
"""

#Completa el contador
#Completa la condición y la actualización para imprimir los números del 1 al 5.
numero = 1
while numero <= 5:
  print(numero)
  numero = numero + 1
#

#Encuentra el ciclo infinito
#El siguiente programa nunca termina. Corrige solo la línea que falta dentro del ciclo
numero = 1
while numero <= 5:
  print(numero)
#

#Control de intentos
#Completa el ciclo para permitir máximo 3 intentos. No modifiques las líneas ya escritas.

Intentos = 0
while Intentos <=3:
  clave = input("Ingrese la Clave:")
  Intentos += 1
  print("Proceso Finalizado")

"""F. Elegir y combinar estructuras
for + if, while + condición y razonamiento sobre flujo

"""

#Combina for + if
#Completa el programa para recorrer del 1 al 12 y mostrar únicamente los múltiplos de 3.
for numero in range(1,13):
  if numero % 3 == 0:
    print(numero)

#Predice antes de ejecutar
#Escribe todas las líneas que producirá el programa.
#Respuesta: 1A,2A, 3B, 4B, 5B,6C,7C
for numero in range(1, 8):
 if numero < 3:
  print(numero, "A")
 elif numero < 6:
  print(numero, "B")
 else:
  print(numero, "C")

"""G. Del pseudocódigo a Python
Conserva la lógica y cambia la representación
"""

#Traduce una decisión
#Completa el código Python para que represente exactamente el pseudocódigo mostrado.
nota = float(input("Nota: "))
if nota >= 3.0:
 print("Aprobado")
else:
 print("No aprobado")

#Traduce una repetición
#Completa el programa Python equivalente al pseudocódigo.
for i in range(1,6):
 print(i)

#Reto integrador
#Combina entrada, repetición y decisión sin utilizar listas ni funciones
# El programa debe solicitar 5 temperaturas.
# Para cada una debe mostrar:
# "Baja" si t < 18
# "Normal" si 18 <= t <= 25
# "Alta" si t > 25
for i in range(5):
  t = float(input("Temperatura: "))
  if t < 18:
    print("Baja")
  elif 18 <= t <= 25:
    print("Normal")
  else:
    print("Alta")